[Issue #118] support one table scan
pixelsdb/pixels-trino pull request #119
Opened 2024-10-09 03:55 UTC by huasiy

Resolves #118

2024-10-09 08:22 UTC, huasiy commented
![image](https://github.com/user-attachments/assets/b6ca6567-c9ba-48fc-b69d-dd68fad4e3e8)

2024-10-09 08:24 UTC, huasiy commented
![image](https://github.com/user-attachments/assets/501f768f-3a4e-4cf4-8e04-4f68ea1c0212)

2024-10-14 05:19 UTC, bianhq requested changes

2024-10-14 05:19 UTC, bianhq commented on connector/pom.xml
> +            <artifactId>pixels-invoker-vhive</artifactId>
Remove this dependency. Multiple invoker dependencies will overwrite the invokers for a worker type.

To solve this problem, we need to modify the InvokerFactory in pixels-common and allow it to load multiple invokers for the same worker type into invokerMap.

2024-10-14 05:19 UTC, bianhq commented on connector/src/main/java/io/pixelsdb/pixels/trino/PixelsWorkerCoordinator.java
> +package io.pixelsdb.pixels.trino;
Add a license header.

2024-10-14 05:19 UTC, bianhq commented on connector/src/main/java/io/pixelsdb/pixels/trino/PixelsWorkerCoordinator.java
> +public class PixelsWorkerCoordinator {
Add a javadoc before class definition, which includes the usage/notice/design of this class and the `@author` and `@create` tags.
Add a new line before {.

2024-10-14 05:19 UTC, bianhq commented on connector/src/main/java/io/pixelsdb/pixels/trino/PixelsWorkerCoordinator.java
> +        if (instance == null) {
Add a new line before {.

2024-10-14 05:19 UTC, bianhq commented on connector/src/main/java/io/pixelsdb/pixels/trino/PixelsWorkerCoordinator.java
> +            workerThread.start();
We should terminate the worker coordinator when the Trino process is shutting down.
I think we can try:
1. terminate the worker coordinator server in the shutdown method of PixelsConnector.
2. add a JVM shutdown hook here to terminate the worker coordinator server when the Trino process is shutting down.

2024-10-15 01:53 UTC, bianhq requested changes

2024-10-15 01:53 UTC, bianhq commented on connector/src/main/java/io/pixelsdb/pixels/trino/PixelsConnectorFactory.java
> +    private WorkerCoordinateServer coordinateServer;
Is this coordinateServer needed?

2024-10-17 02:59 UTC, huasiy commented on connector/src/main/java/io/pixelsdb/pixels/trino/PixelsConnectorFactory.java
> +    private WorkerCoordinateServer coordinateServer;
Yes, no need.

2024-10-17 03:38 UTC, bianhq approved these changes
LGTM.

2024-10-17 03:39 UTC, merged